import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, Stack, Switch, TextField } from '@mui/material';
import { useEffect, useState, type FormEvent } from 'react';
import { api } from '../api/client'; import type { Source, SourceInput } from '../api/types';
import { splitPatterns } from '../utils/forms';
const DEFAULT_INCLUDES = ['**/*.pdf', '**/*.docx', '**/*.txt', '**/*.md'];
const DEFAULT_EXCLUDES = ['**/~$*', '**/.*', '**/tmp/**', '**/archive/**'];
export function SourceDialog({ open, source, onClose, onSaved }: { open: boolean; source: Source | null; onClose: () => void; onSaved: () => void }) {
  const [name, setName] = useState(''); const [path, setPath] = useState('/data/sources/'); const [includes, setIncludes] = useState(DEFAULT_INCLUDES.join('\n')); const [excludes, setExcludes] = useState(DEFAULT_EXCLUDES.join('\n')); const [interval, setInterval] = useState(300); const [enabled, setEnabled] = useState(true); const [error, setError] = useState(''); const [validation, setValidation] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (source) { setName(source.name); setPath(source.configuration.path); setIncludes(source.configuration.include_patterns.join('\n')); setExcludes(source.configuration.exclude_patterns.join('\n')); setInterval(source.configuration.scan_interval_seconds); setEnabled(source.enabled); } else { setName(''); setPath('/data/sources/'); setIncludes(DEFAULT_INCLUDES.join('\n')); setExcludes(DEFAULT_EXCLUDES.join('\n')); setInterval(300); setEnabled(true); } setError(''); setValidation(''); }, [source, open]);
  const input = (): SourceInput => ({ plugin_type: 'filesystem_documents', name, enabled, configuration: { path, include_patterns: splitPatterns(includes), exclude_patterns: splitPatterns(excludes), scan_interval_seconds: interval } });
  const validate = async () => { setError(''); setValidation(''); try { const result = await api.validateSourceInput(input()); setValidation(result.message); } catch (e) { setError(e instanceof Error ? e.message : 'Validation failed'); } };
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { const value = input(); if (source) await api.updateSource(source.id, { name: value.name, enabled: value.enabled, configuration: value.configuration }); else await api.createSource(value); onSaved(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save source'); } finally { setSaving(false); } };
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm" PaperProps={{ component: 'form', onSubmit: submit }}><DialogTitle>{source ? 'Edit filesystem source' : 'Add filesystem source'}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}>{error && <Alert severity="error">{error}</Alert>}{validation && <Alert severity="success">{validation}</Alert>}
    <TextField required label="Name" value={name} onChange={(e) => setName(e.target.value)} /><FormControlLabel control={<Switch checked={enabled} onChange={(e) => setEnabled(e.target.checked)} />} label="Enabled" />
    <TextField required label="Path" value={path} onChange={(e) => { setPath(e.target.value); setValidation(''); }} helperText="Must be /data/sources or one of its subdirectories. The Docker mount cannot be changed here." />
    <TextField required multiline minRows={4} label="Include patterns" value={includes} onChange={(e) => setIncludes(e.target.value)} helperText="One glob pattern per line" />
    <TextField multiline minRows={4} label="Exclude patterns" value={excludes} onChange={(e) => setExcludes(e.target.value)} helperText="One glob pattern per line" />
    <TextField required type="number" label="Scan interval (seconds)" value={interval} onChange={(e) => setInterval(Number(e.target.value))} inputProps={{ min: 30, max: 86400 }} />
  </Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button onClick={() => void validate()}>Test configuration</Button><Button type="submit" variant="contained" disabled={saving}>Save source</Button></DialogActions></Dialog>;
}
