"""connector inventory phase one

Revision ID: 59ac2e409f69
Revises: 20260721_0006
Create Date: 2026-07-27 18:31:30.778866
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.infrastructure.database import types

revision: str = "59ac2e409f69"
down_revision: str | None = "20260721_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cmdb_datasets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("current_version_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("retired_at", types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", types.UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["current_version_id"],
            ["cmdb_dataset_versions.id"],
            name=op.f("fk_cmdb_datasets_current_version_id_cmdb_dataset_versions"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cmdb_datasets")),
    )
    with op.batch_alter_table("cmdb_datasets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cmdb_datasets_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_cmdb_datasets_status"), ["status"], unique=False)

    op.create_table(
        "cmdb_mapping_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("mapping_json", sa.JSON(), nullable=False),
        sa.Column("normalization_json", sa.JSON(), nullable=False),
        sa.Column("required_field_policy", sa.String(length=64), nullable=False),
        sa.Column("created_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cmdb_mapping_profiles")),
        sa.UniqueConstraint("name", name=op.f("uq_cmdb_mapping_profiles_name")),
    )
    op.create_table(
        "inventory_assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_name", sa.String(length=500), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("fqdn", sa.String(length=500), nullable=True),
        sa.Column("primary_ip", sa.String(length=64), nullable=True),
        sa.Column("additional_ips_json", sa.JSON(), nullable=False),
        sa.Column("asset_type", sa.String(length=255), nullable=True),
        sa.Column("environment", sa.String(length=255), nullable=True),
        sa.Column("operating_system", sa.String(length=500), nullable=True),
        sa.Column("cloud_provider", sa.String(length=255), nullable=True),
        sa.Column("cloud_instance_id", sa.String(length=500), nullable=True),
        sa.Column("serial_number", sa.String(length=500), nullable=True),
        sa.Column("asset_tag", sa.String(length=500), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("application", sa.String(length=500), nullable=True),
        sa.Column("business_owner", sa.String(length=500), nullable=True),
        sa.Column("technical_owner", sa.String(length=500), nullable=True),
        sa.Column("lifecycle_status", sa.String(length=100), nullable=True),
        sa.Column("first_seen_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("created_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("retired_at", types.UTCDateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_assets")),
    )
    with op.batch_alter_table("inventory_assets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_inventory_assets_asset_tag"), ["asset_tag"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_assets_asset_type"), ["asset_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_assets_canonical_name"), ["canonical_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_assets_cloud_instance_id"), ["cloud_instance_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_assets_environment"), ["environment"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_inventory_assets_fqdn"), ["fqdn"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_inventory_assets_hostname"), ["hostname"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_assets_lifecycle_status"), ["lifecycle_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_assets_primary_ip"), ["primary_ip"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_assets_serial_number"), ["serial_number"], unique=False
        )

    op.create_table(
        "prometheus_configurations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("base_url", sa.String(length=1000), nullable=False),
        sa.Column("auth_type", sa.String(length=32), nullable=False),
        sa.Column("username", sa.String(length=500), nullable=True),
        sa.Column("encrypted_secret", sa.Text(), nullable=True),
        sa.Column("tls_verify", sa.Boolean(), nullable=False),
        sa.Column("custom_ca_path", sa.Text(), nullable=True),
        sa.Column("request_timeout_seconds", sa.Float(), nullable=False),
        sa.Column("scan_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_successful_scan_at", types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("last_failed_scan_at", types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=2000), nullable=True),
        sa.Column("target_count", sa.Integer(), nullable=False),
        sa.Column("healthy_target_count", sa.Integer(), nullable=False),
        sa.Column("unhealthy_target_count", sa.Integer(), nullable=False),
        sa.Column("created_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prometheus_configurations")),
        sa.UniqueConstraint("name", name=op.f("uq_prometheus_configurations_name")),
    )
    with op.batch_alter_table("prometheus_configurations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_prometheus_configurations_enabled"), ["enabled"], unique=False
        )

    op.create_table(
        "cmdb_dataset_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("stored_filename", sa.String(length=255), nullable=False),
        sa.Column("stored_path", sa.Text(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("file_type", sa.String(length=16), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("sheet_name", sa.String(length=255), nullable=True),
        sa.Column("header_row", sa.Integer(), nullable=True),
        sa.Column("mapping_profile_id", sa.Uuid(), nullable=True),
        sa.Column("mapping_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("valid_rows", sa.Integer(), nullable=False),
        sa.Column("invalid_rows", sa.Integer(), nullable=False),
        sa.Column("duplicate_rows", sa.Integer(), nullable=False),
        sa.Column("imported_at", types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("created_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["cmdb_datasets.id"],
            name=op.f("fk_cmdb_dataset_versions_dataset_id_cmdb_datasets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["mapping_profile_id"],
            ["cmdb_mapping_profiles.id"],
            name=op.f("fk_cmdb_dataset_versions_mapping_profile_id_cmdb_mapping_profiles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cmdb_dataset_versions")),
        sa.UniqueConstraint(
            "dataset_id", "version_number", name=op.f("uq_cmdb_dataset_versions_dataset_id")
        ),
        sa.UniqueConstraint(
            "stored_filename", name=op.f("uq_cmdb_dataset_versions_stored_filename")
        ),
    )
    with op.batch_alter_table("cmdb_dataset_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cmdb_dataset_versions_checksum"), ["checksum"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cmdb_dataset_versions_dataset_id"), ["dataset_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cmdb_dataset_versions_status"), ["status"], unique=False
        )

    op.create_table(
        "inventory_observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=True),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_configuration_id", sa.Uuid(), nullable=True),
        sa.Column("source_record_id", sa.String(length=500), nullable=False),
        sa.Column("observed_fields_json", sa.JSON(), nullable=False),
        sa.Column("raw_reference", sa.String(length=1000), nullable=False),
        sa.Column("raw_checksum", sa.String(length=64), nullable=False),
        sa.Column("observed_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("first_seen_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("created_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["inventory_assets.id"],
            name=op.f("fk_inventory_observations_asset_id_inventory_assets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_observations")),
        sa.UniqueConstraint(
            "source_type", "source_record_id", name=op.f("uq_inventory_observations_source_type")
        ),
    )
    with op.batch_alter_table("inventory_observations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_inventory_observations_asset_id"), ["asset_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_observations_source_configuration_id"),
            ["source_configuration_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_observations_source_record_id"),
            ["source_record_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_observations_source_type"), ["source_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_observations_status"), ["status"], unique=False
        )

    op.create_table(
        "cmdb_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dataset_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_row_number", sa.Integer(), nullable=False),
        sa.Column("source_record_key", sa.String(length=500), nullable=True),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("fqdn", sa.String(length=500), nullable=True),
        sa.Column("primary_ip", sa.String(length=64), nullable=True),
        sa.Column("cloud_instance_id", sa.String(length=500), nullable=True),
        sa.Column("serial_number", sa.String(length=500), nullable=True),
        sa.Column("asset_tag", sa.String(length=500), nullable=True),
        sa.Column("normalized_fields_json", sa.JSON(), nullable=False),
        sa.Column("raw_fields_json", sa.JSON(), nullable=False),
        sa.Column("validation_status", sa.String(length=32), nullable=False),
        sa.Column("validation_errors_json", sa.JSON(), nullable=False),
        sa.Column("row_checksum", sa.String(length=64), nullable=False),
        sa.Column("created_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["cmdb_dataset_versions.id"],
            name=op.f("fk_cmdb_records_dataset_version_id_cmdb_dataset_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cmdb_records")),
        sa.UniqueConstraint(
            "dataset_version_id",
            "source_row_number",
            name=op.f("uq_cmdb_records_dataset_version_id"),
        ),
    )
    with op.batch_alter_table("cmdb_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cmdb_records_asset_tag"), ["asset_tag"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_cmdb_records_cloud_instance_id"), ["cloud_instance_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cmdb_records_dataset_version_id"), ["dataset_version_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_cmdb_records_fqdn"), ["fqdn"], unique=False)
        batch_op.create_index(batch_op.f("ix_cmdb_records_hostname"), ["hostname"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_cmdb_records_primary_ip"), ["primary_ip"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cmdb_records_row_checksum"), ["row_checksum"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cmdb_records_serial_number"), ["serial_number"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cmdb_records_source_record_key"), ["source_record_key"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cmdb_records_validation_status"), ["validation_status"], unique=False
        )

    op.create_table(
        "inventory_conflicts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=True),
        sa.Column("observation_id", sa.Uuid(), nullable=True),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("source_values_json", sa.JSON(), nullable=False),
        sa.Column("preferred_value", sa.Text(), nullable=True),
        sa.Column("resolution_status", sa.String(length=32), nullable=False),
        sa.Column("resolution_reason", sa.Text(), nullable=True),
        sa.Column("resolved_at", types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["inventory_assets.id"],
            name=op.f("fk_inventory_conflicts_asset_id_inventory_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["inventory_observations.id"],
            name=op.f("fk_inventory_conflicts_observation_id_inventory_observations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["users.id"],
            name=op.f("fk_inventory_conflicts_resolved_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_conflicts")),
    )
    with op.batch_alter_table("inventory_conflicts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_inventory_conflicts_asset_id"), ["asset_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_conflicts_field_name"), ["field_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_conflicts_observation_id"), ["observation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_conflicts_resolution_status"),
            ["resolution_status"],
            unique=False,
        )

    op.create_table(
        "inventory_correlations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("observation_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=True),
        sa.Column("match_method", sa.String(length=100), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("decision_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("reviewed_at", types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["inventory_assets.id"],
            name=op.f("fk_inventory_correlations_asset_id_inventory_assets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["inventory_observations.id"],
            name=op.f("fk_inventory_correlations_observation_id_inventory_observations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
            name=op.f("fk_inventory_correlations_reviewed_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_correlations")),
    )
    with op.batch_alter_table("inventory_correlations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_inventory_correlations_asset_id"), ["asset_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_correlations_decision_type"), ["decision_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_correlations_observation_id"), ["observation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_correlations_status"), ["status"], unique=False
        )

    op.create_table(
        "inventory_identities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=True),
        sa.Column("observation_id", sa.Uuid(), nullable=False),
        sa.Column("identity_type", sa.String(length=64), nullable=False),
        sa.Column("original_value", sa.String(length=1000), nullable=False),
        sa.Column("normalized_value", sa.String(length=1000), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("first_seen_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["inventory_assets.id"],
            name=op.f("fk_inventory_identities_asset_id_inventory_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["inventory_observations.id"],
            name=op.f("fk_inventory_identities_observation_id_inventory_observations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_identities")),
        sa.UniqueConstraint(
            "observation_id",
            "identity_type",
            "normalized_value",
            name=op.f("uq_inventory_identities_observation_id"),
        ),
    )
    with op.batch_alter_table("inventory_identities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_inventory_identities_asset_id"), ["asset_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_identities_identity_type"), ["identity_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_identities_normalized_value"),
            ["normalized_value"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_identities_observation_id"), ["observation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_identities_source_type"), ["source_type"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inventory_identities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_identities_source_type"))
        batch_op.drop_index(batch_op.f("ix_inventory_identities_observation_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_identities_normalized_value"))
        batch_op.drop_index(batch_op.f("ix_inventory_identities_identity_type"))
        batch_op.drop_index(batch_op.f("ix_inventory_identities_asset_id"))

    op.drop_table("inventory_identities")
    with op.batch_alter_table("inventory_correlations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_correlations_status"))
        batch_op.drop_index(batch_op.f("ix_inventory_correlations_observation_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_correlations_decision_type"))
        batch_op.drop_index(batch_op.f("ix_inventory_correlations_asset_id"))

    op.drop_table("inventory_correlations")
    with op.batch_alter_table("inventory_conflicts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_conflicts_resolution_status"))
        batch_op.drop_index(batch_op.f("ix_inventory_conflicts_observation_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_conflicts_field_name"))
        batch_op.drop_index(batch_op.f("ix_inventory_conflicts_asset_id"))

    op.drop_table("inventory_conflicts")
    with op.batch_alter_table("cmdb_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cmdb_records_validation_status"))
        batch_op.drop_index(batch_op.f("ix_cmdb_records_source_record_key"))
        batch_op.drop_index(batch_op.f("ix_cmdb_records_serial_number"))
        batch_op.drop_index(batch_op.f("ix_cmdb_records_row_checksum"))
        batch_op.drop_index(batch_op.f("ix_cmdb_records_primary_ip"))
        batch_op.drop_index(batch_op.f("ix_cmdb_records_hostname"))
        batch_op.drop_index(batch_op.f("ix_cmdb_records_fqdn"))
        batch_op.drop_index(batch_op.f("ix_cmdb_records_dataset_version_id"))
        batch_op.drop_index(batch_op.f("ix_cmdb_records_cloud_instance_id"))
        batch_op.drop_index(batch_op.f("ix_cmdb_records_asset_tag"))

    op.drop_table("cmdb_records")
    with op.batch_alter_table("inventory_observations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_observations_status"))
        batch_op.drop_index(batch_op.f("ix_inventory_observations_source_type"))
        batch_op.drop_index(batch_op.f("ix_inventory_observations_source_record_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_observations_source_configuration_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_observations_asset_id"))

    op.drop_table("inventory_observations")
    with op.batch_alter_table("cmdb_dataset_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cmdb_dataset_versions_status"))
        batch_op.drop_index(batch_op.f("ix_cmdb_dataset_versions_dataset_id"))
        batch_op.drop_index(batch_op.f("ix_cmdb_dataset_versions_checksum"))

    op.drop_table("cmdb_dataset_versions")
    with op.batch_alter_table("prometheus_configurations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prometheus_configurations_enabled"))

    op.drop_table("prometheus_configurations")
    with op.batch_alter_table("inventory_assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_assets_serial_number"))
        batch_op.drop_index(batch_op.f("ix_inventory_assets_primary_ip"))
        batch_op.drop_index(batch_op.f("ix_inventory_assets_lifecycle_status"))
        batch_op.drop_index(batch_op.f("ix_inventory_assets_hostname"))
        batch_op.drop_index(batch_op.f("ix_inventory_assets_fqdn"))
        batch_op.drop_index(batch_op.f("ix_inventory_assets_environment"))
        batch_op.drop_index(batch_op.f("ix_inventory_assets_cloud_instance_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_assets_canonical_name"))
        batch_op.drop_index(batch_op.f("ix_inventory_assets_asset_type"))
        batch_op.drop_index(batch_op.f("ix_inventory_assets_asset_tag"))

    op.drop_table("inventory_assets")
    op.drop_table("cmdb_mapping_profiles")
    with op.batch_alter_table("cmdb_datasets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cmdb_datasets_status"))
        batch_op.drop_index(batch_op.f("ix_cmdb_datasets_name"))

    op.drop_table("cmdb_datasets")
    # ### end Alembic commands ###
