import {
  Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle,
  FormControl, InputLabel, MenuItem, Paper, Select, Stack, Table, TableBody,
  TableCell, TableContainer, TableHead, TablePagination, TableRow, TextField,
  Typography,
} from '@mui/material';
import { useCallback, useEffect, useState } from 'react';

import { api } from '../api/client';
import type { InventoryDetail, InventoryItem } from '../api/types';
import { useAuth } from '../auth/AuthContext';
import { LoadingState } from '../components/LoadingState';
import { useToast } from '../components/ToastProvider';
import { formatTimestamp } from '../utils/time';

export function InventoryPage() {
  const { user } = useAuth(); const admin = user?.role === 'administrator'; const toast = useToast();
  const [items, setItems] = useState<InventoryItem[]>([]); const [total, setTotal] = useState(0);
  const [page, setPage] = useState(0); const [search, setSearch] = useState(''); const [coverage, setCoverage] = useState('');
  const [environment, setEnvironment] = useState(''); const [assetType, setAssetType] = useState(''); const [lifecycle, setLifecycle] = useState(''); const [health, setHealth] = useState(''); const [correlation, setCorrelation] = useState('');
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [detail, setDetail] = useState<InventoryDetail | null>(null);
  const [decisionObservation, setDecisionObservation] = useState<string | null>(null); const [decisionAsset, setDecisionAsset] = useState('');
  const load = useCallback(async () => { try { setLoading(true); const query = new URLSearchParams({ page: String(page + 1), page_size: '25' }); if (search) query.set('search', search); if (coverage) query.set('coverage', coverage); if (environment) query.set('environment', environment); if (assetType) query.set('asset_type', assetType); if (lifecycle) query.set('lifecycle_status', lifecycle); if (health) query.set('prometheus_health', health); if (correlation) query.set('correlation_status', correlation); const result = await api.inventory(query.toString()); setItems(result.items); setTotal(result.total); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Inventory could not be loaded'); } finally { setLoading(false); } }, [page, search, coverage, environment, assetType, lifecycle, health, correlation]);
  useEffect(() => { void load(); }, [load]);
  return <Stack spacing={3}><Box><Typography variant="h4" fontWeight={800}>Inventory</Typography><Typography color="text.secondary">One canonical local view combining declared CMDB assets with observed Prometheus targets.</Typography></Box>
    <Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} useFlexGap flexWrap="wrap"><TextField label="Search inventory" value={search} onChange={(event) => { setSearch(event.target.value); setPage(0); }} /><FormControl sx={{ minWidth: 240 }}><InputLabel>Source coverage</InputLabel><Select label="Source coverage" value={coverage} onChange={(event) => { setCoverage(event.target.value); setPage(0); }}><MenuItem value="">All coverage</MenuItem><MenuItem value="Declared and monitored">Declared and monitored</MenuItem><MenuItem value="Declared but not monitored">Declared but not monitored</MenuItem><MenuItem value="Observed but missing from CMDB">Observed but missing from CMDB</MenuItem></Select></FormControl><TextField label="Environment" value={environment} onChange={(event) => setEnvironment(event.target.value)} /><TextField label="Asset type" value={assetType} onChange={(event) => setAssetType(event.target.value)} /><TextField label="Lifecycle status" value={lifecycle} onChange={(event) => setLifecycle(event.target.value)} /><FormControl sx={{ minWidth: 180 }}><InputLabel>Prometheus health</InputLabel><Select label="Prometheus health" value={health} onChange={(event) => setHealth(event.target.value)}><MenuItem value="">All</MenuItem><MenuItem value="healthy">Healthy</MenuItem><MenuItem value="unhealthy">Unhealthy</MenuItem><MenuItem value="not_observed">Not observed</MenuItem><MenuItem value="unknown">Unknown</MenuItem></Select></FormControl><FormControl sx={{ minWidth: 180 }}><InputLabel>Correlation</InputLabel><Select label="Correlation" value={correlation} onChange={(event) => setCorrelation(event.target.value)}><MenuItem value="">All</MenuItem><MenuItem value="matched">Matched</MenuItem><MenuItem value="ambiguous">Ambiguous</MenuItem><MenuItem value="unmatched">Unmatched</MenuItem></Select></FormControl></Stack>
    {error && <Alert severity="error">{error}</Alert>}
    {loading ? <LoadingState label="Loading inventory" /> : <Paper variant="outlined"><TableContainer><Table><TableHead><TableRow><TableCell>Asset</TableCell><TableCell>Type</TableCell><TableCell>Environment</TableCell><TableCell>CMDB</TableCell><TableCell>Metrics</TableCell><TableCell>Prometheus health</TableCell><TableCell>Last metrics seen</TableCell><TableCell>Correlation</TableCell><TableCell>Lifecycle</TableCell></TableRow></TableHead><TableBody>{items.map((item) => <TableRow key={item.id} hover onClick={() => { if (item.id.startsWith('observation:')) { if (admin) setDecisionObservation(item.id.replace('observation:', '')); } else void api.inventoryDetail(item.id).then(setDetail); }} sx={{ cursor: 'pointer' }}><TableCell><Typography fontWeight={600}>{item.canonical_name}</Typography><Typography variant="caption" color="text.secondary">{item.fqdn ?? item.primary_ip ?? item.hostname ?? 'No display identity'}</Typography></TableCell><TableCell>{item.asset_type ?? 'Unknown'}</TableCell><TableCell>{item.environment ?? 'Unknown'}</TableCell><TableCell>{item.sources.includes('cmdb') ? 'Observed' : 'Not observed'}</TableCell><TableCell>{item.sources.includes('prometheus') ? 'Observed' : 'Not observed'}</TableCell><TableCell><Chip size="small" label={item.prometheus_health.replaceAll('_', ' ')} color={item.prometheus_health === 'unhealthy' ? 'error' : item.prometheus_health === 'healthy' ? 'success' : 'default'} /></TableCell><TableCell>{formatTimestamp(item.last_metrics_seen)}</TableCell><TableCell>{item.correlation_status}</TableCell><TableCell>{item.lifecycle_status ?? 'Unknown'}</TableCell></TableRow>)}</TableBody></Table></TableContainer><TablePagination component="div" count={total} page={page} rowsPerPage={25} rowsPerPageOptions={[25]} onPageChange={(_, value) => setPage(value)} /></Paper>}
    <Dialog open={Boolean(detail)} onClose={() => setDetail(null)} fullWidth maxWidth="md"><DialogTitle>Asset detail</DialogTitle><DialogContent dividers>{detail && <Stack spacing={3}><section><Typography variant="h6">Canonical fields</Typography>{Object.entries(detail.asset).filter(([name, value]) => value !== null && !['id', 'created_at', 'updated_at'].includes(name)).map(([name, value]) => <Typography key={name}><strong>{name.replaceAll('_', ' ')}:</strong> {String(value)}</Typography>)}</section><section><Typography variant="h6">Identities</Typography>{detail.identities.map((identity, index) => <Typography key={`${identity.identity_type}-${index}`}>{identity.identity_type}: {identity.original_value} <Typography component="span" color="text.secondary">({identity.source_type}, normalized: {identity.normalized_value})</Typography></Typography>)}</section><section><Typography variant="h6">Source observations</Typography>{detail.observations.map((observation) => <Paper key={observation.id} variant="outlined" sx={{ p: 2, mt: 1 }}><Typography fontWeight={700}>{observation.source_type}</Typography><Typography variant="body2">{observation.raw_reference}</Typography><Typography variant="body2">Last seen: {formatTimestamp(observation.last_seen_at)}</Typography>{observation.source_type === 'prometheus' && <><Typography variant="body2">Health: {String(observation.observed_fields.health ?? 'Unknown')} · Last scrape: {String(observation.observed_fields.last_scrape ?? 'Unknown')} · Error: {String(observation.observed_fields.last_scrape_error ?? 'None')}</Typography>{admin && <Button color="warning" size="small" onClick={() => void api.decideCorrelation(observation.id, null, 'split').then(() => { setDetail(null); toast.show('Prometheus observation unlinked.', 'success'); return load(); })}>Unlink observation</Button>}</>}</Paper>)}</section><section><Typography variant="h6">Conflicts</Typography>{detail.conflicts.length === 0 ? <Typography color="text.secondary">No open conflicts.</Typography> : detail.conflicts.map((conflict) => <Alert key={conflict.id} severity="warning" sx={{ mt: 1 }}>{conflict.field_name}: {JSON.stringify(conflict.source_values)}</Alert>)}</section></Stack>}</DialogContent><DialogActions><Button onClick={() => setDetail(null)}>Close</Button></DialogActions></Dialog>
    <Dialog open={Boolean(decisionObservation)} onClose={() => setDecisionObservation(null)} fullWidth maxWidth="sm"><DialogTitle>Review correlation</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><Typography>Link this observed Prometheus target to a declared asset, or preserve it as rejected.</Typography><FormControl fullWidth><InputLabel>Canonical asset</InputLabel><Select label="Canonical asset" value={decisionAsset} onChange={(event) => setDecisionAsset(event.target.value)}>{items.filter((item) => !item.id.startsWith('observation:')).map((item) => <MenuItem key={item.id} value={item.id}>{item.canonical_name}</MenuItem>)}</Select></FormControl></Stack></DialogContent><DialogActions><Button onClick={() => setDecisionObservation(null)}>Cancel</Button><Button color="warning" onClick={() => { if (decisionObservation) void api.decideCorrelation(decisionObservation, null, 'rejected').then(() => { setDecisionObservation(null); toast.show('Correlation rejected.', 'success'); return load(); }); }}>Reject</Button><Button variant="contained" disabled={!decisionAsset} onClick={() => { if (decisionObservation) void api.decideCorrelation(decisionObservation, decisionAsset, 'matched').then(() => { setDecisionObservation(null); setDecisionAsset(''); toast.show('Observation linked.', 'success'); return load(); }); }}>Link asset</Button></DialogActions></Dialog>
  </Stack>;
}
