import DownloadIcon from '@mui/icons-material/Download';
import { Alert, Button, MenuItem, Pagination, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { useCallback, useEffect, useState } from 'react';
import { api } from '../api/client'; import type { PaginatedLogs } from '../api/types'; import { LoadingState } from '../components/LoadingState'; import { useToast } from '../components/ToastProvider';
export function LogsPage() { const toast = useToast(); const [data, setData] = useState<PaginatedLogs | null>(null); const [level, setLevel] = useState(''); const [component, setComponent] = useState(''); const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [error, setError] = useState('');
  const load = useCallback(() => { const query = new URLSearchParams({ page: String(page), page_size: '50' }); if (level) query.set('level', level); if (component) query.set('component', component); if (search) query.set('search', search); void api.logs(query.toString()).then(setData).catch((e: Error) => setError(e.message)); }, [page, level, component, search]);
  useEffect(load, [load]);
  return <Stack spacing={3}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between"><div><Typography variant="h4" fontWeight={700}>Logs</Typography><Typography color="text.secondary">Recent structured application logs</Typography></div><Button startIcon={<DownloadIcon />} onClick={() => void api.downloadLogs().catch((e: Error) => toast.show(e.message, 'error'))}>Download</Button></Stack>
    <Stack direction={{ xs: 'column', md: 'row' }} spacing={2}><TextField select label="Level" value={level} onChange={(e) => { setLevel(e.target.value); setPage(1); }} sx={{ minWidth: 140 }}><MenuItem value="">All</MenuItem>{['DEBUG','INFO','WARNING','ERROR'].map((value) => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField><TextField label="Component" value={component} onChange={(e) => { setComponent(e.target.value); setPage(1); }} /><TextField fullWidth label="Search logs" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} /></Stack>
    {error ? <Alert severity="error">{error}</Alert> : !data ? <LoadingState /> : data.items.length === 0 ? <Alert severity="info">No logs match the selected filters.</Alert> : <><TableContainer component={Paper}><Table><TableHead><TableRow><TableCell>Time</TableCell><TableCell>Level</TableCell><TableCell>Component</TableCell><TableCell>Message</TableCell></TableRow></TableHead><TableBody>{data.items.map((item) => <TableRow key={item.id}><TableCell>{new Date(item.created_at).toLocaleString()}</TableCell><TableCell>{item.level}</TableCell><TableCell>{item.component}</TableCell><TableCell>{item.message}</TableCell></TableRow>)}</TableBody></Table></TableContainer><Pagination page={page} count={Math.max(1, Math.ceil(data.total / data.page_size))} onChange={(_, value) => setPage(value)} /></>}
  </Stack>;
}
