import { Alert, Button, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { useEffect, useState, type FormEvent } from 'react';
import { api } from '../api/client'; import type { ProductSettings } from '../api/types'; import { useAuth } from '../auth/AuthContext'; import { LoadingState } from '../components/LoadingState'; import { useToast } from '../components/ToastProvider';
export function SettingsPage() { const { user } = useAuth(); const toast = useToast(); const [data, setData] = useState<ProductSettings | null>(null); const [error, setError] = useState(''); const admin = user?.role === 'administrator';
  useEffect(() => { void api.settings().then(setData).catch((e: Error) => setError(e.message)); }, []);
  const save = async (event: FormEvent) => { event.preventDefault(); if (!data) return; try { setData(await api.updateSettings({ connector_display_name: data.connector_display_name, environment_label: data.environment_label, log_level: data.log_level, timezone: data.timezone, saas_url: data.saas_url || null })); toast.show('Settings saved', 'success'); } catch (e) { setError(e instanceof Error ? e.message : 'Save failed'); } };
  if (!data && !error) return <LoadingState />;
  return <Stack spacing={3}><div><Typography variant="h4" fontWeight={700}>Settings</Typography><Typography color="text.secondary">UI-managed connector configuration</Typography></div>{error && <Alert severity="error">{error}</Alert>}{data && <>
    <Paper component="form" onSubmit={save} variant="outlined" sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h6">General</Typography><TextField disabled={!admin} label="Connector display name" value={data.connector_display_name} onChange={(e) => setData({ ...data, connector_display_name: e.target.value })} /><TextField disabled={!admin} label="Environment label" value={data.environment_label} onChange={(e) => setData({ ...data, environment_label: e.target.value })} /><TextField select disabled={!admin} label="Log level" value={data.log_level} onChange={(e) => setData({ ...data, log_level: e.target.value })}>{['DEBUG','INFO','WARNING','ERROR'].map((value) => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField><TextField disabled={!admin} label="Time zone display preference" value={data.timezone} onChange={(e) => setData({ ...data, timezone: e.target.value })} />{admin && <Button type="submit" variant="contained" sx={{ alignSelf: 'flex-start' }}>Save settings</Button>}</Stack></Paper>
    <Paper variant="outlined" sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h6">SaaS Registration</Typography><Typography>Status: {data.saas_status.replaceAll('_', ' ')}</Typography><Typography>Connector ID: {data.connector_id ?? 'Not assigned'}</Typography><Typography>Tenant ID: {data.tenant_id ?? 'Not assigned'}</Typography><TextField disabled={!admin} label="PEKA SaaS URL" value={data.saas_url ?? ''} onChange={(e) => setData({ ...data, saas_url: e.target.value })} /><Alert severity="info">The PEKA SaaS registration API is not configured in this release. Registration controls remain unavailable until a real endpoint is provided.</Alert><Button disabled variant="outlined" sx={{ alignSelf: 'flex-start' }}>Register connector</Button></Stack></Paper>
  </>}</Stack>;
}
