import { Alert, Button, CircularProgress, Divider, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { useEffect, useRef, useState, type FormEvent } from 'react';

import { api } from '../api/client';
import type { ProductSettings, TrustedCertificateAuthority } from '../api/types';
import { useAuth } from '../auth/AuthContext';
import { ConnectionStatusBadge } from '../components/ConnectionStatusBadge';
import { LoadingState } from '../components/LoadingState';
import { useToast } from '../components/ToastProvider';
import { formatTimestamp, relativeTimestamp } from '../utils/time';
import { RegistrationAttemptGuard, registrationErrorPresentation } from '../utils/registration';
import { customerFacingText } from '../utils/displayText';

export function SettingsPage() {
  const { user } = useAuth(); const toast = useToast(); const admin = user?.role === 'administrator';
  const [data, setData] = useState<ProductSettings | null>(null); const [token, setToken] = useState('');
  const [certificates, setCertificates] = useState<TrustedCertificateAuthority[]>([]);
  const [certificateName, setCertificateName] = useState('');
  const [certificateFile, setCertificateFile] = useState<File | null>(null);
  const [error, setError] = useState(''); const [errorGuidance, setErrorGuidance] = useState(''); const [busy, setBusy] = useState(false);
  const registrationGuard = useRef(new RegistrationAttemptGuard());
  useEffect(() => {
    void api.settings().then(setData).catch((e: Error) => setError(e.message));
    void api.trustedCertificates().then(setCertificates).catch((e: Error) => setError(e.message));
  }, []);
  const save = async (event: FormEvent) => { event.preventDefault(); if (!data) return; setBusy(true); try { const updated = await api.updateSettings({ connector_display_name: data.connector_display_name, environment_label: data.environment_label, log_level: data.log_level }); setData({ ...updated, saas_url: data.saas_url }); if (updated.metadata_sync_warning) toast.show(updated.metadata_sync_warning, 'warning'); else toast.show('Settings saved', 'success'); } catch (e) { setError(e instanceof Error ? e.message : 'Save failed'); } finally { setBusy(false); } };
  const test = async () => { if (!data?.saas_url) return; setBusy(true); try { const result = await api.testSaas(data.saas_url); toast.show(customerFacingText(result.message), 'success'); } catch (e) { toast.show(customerFacingText(e instanceof Error ? e.message : 'Connectivity test failed'), 'error'); } finally { setBusy(false); } };
  const register = async (reregister: boolean) => { if (!data?.saas_url || !token) return; if (reregister && !window.confirm('Re-register with a new token? Existing credentials remain active unless registration succeeds.')) return; try { const body = { saas_url: data.saas_url, registration_token: token, confirmed: reregister }; const updated = await registrationGuard.current.run(() => reregister ? api.reregisterSaas(body) : api.registerSaas(body), () => { setBusy(true); setError(''); setErrorGuidance(''); }, () => { setToken(''); setBusy(false); }); if (!updated) return; setData(updated); toast.show('Registration accepted; awaiting first heartbeat', 'success'); } catch (e) { const presentation = registrationErrorPresentation(e); setError(customerFacingText(presentation.message)); setErrorGuidance(customerFacingText(presentation.guidance ?? '')); } };
  const retry = async () => { setBusy(true); try { setData(await api.retryHeartbeat()); toast.show('Heartbeat attempt completed', 'success'); } catch (e) { setError(e instanceof Error ? e.message : 'Heartbeat retry failed'); } finally { setBusy(false); } };
  const unregister = async () => { if (!window.confirm("Local unregister removes this appliance's local PEKA credentials. It does not delete or retire the connector record in PEKA. Continue?")) return; setBusy(true); try { setData(await api.unregisterSaas()); setToken(''); toast.show('Local registration removed', 'success'); } catch (e) { setError(e instanceof Error ? e.message : 'Unregister failed'); } finally { setBusy(false); } };
  const uploadCertificate = async () => { if (!certificateFile || !certificateName) return; setBusy(true); try { await api.uploadTrustedCertificate(certificateName, certificateFile); setCertificates(await api.trustedCertificates()); setCertificateName(''); setCertificateFile(null); toast.show('Trusted certificate authority added.', 'success'); } catch (e) { setError(e instanceof Error ? e.message : 'Certificate upload failed'); } finally { setBusy(false); } };
  const setCertificateState = async (certificate: TrustedCertificateAuthority) => { setBusy(true); try { await api.setTrustedCertificateState(certificate.id, !certificate.enabled); setCertificates(await api.trustedCertificates()); } catch (e) { setError(e instanceof Error ? e.message : 'Certificate update failed'); } finally { setBusy(false); } };
  const deleteCertificate = async (certificate: TrustedCertificateAuthority) => { if (!window.confirm(`Delete trusted CA “${certificate.name}”? Connections that depend on it may fail.`)) return; setBusy(true); try { await api.deleteTrustedCertificate(certificate.id); setCertificates(await api.trustedCertificates()); toast.show('Trusted certificate authority deleted.', 'success'); } catch (e) { setError(e instanceof Error ? e.message : 'Certificate deletion failed'); } finally { setBusy(false); } };
  if (!data && !error) return <LoadingState />;
  if (!data) return <Alert severity="error">{error}</Alert>;
  const registered = Boolean(data.connector_id);
  return <Stack spacing={3}>
    <div><Typography variant="h4" fontWeight={700}>Settings</Typography><Typography color="text.secondary">UI-managed connector configuration</Typography></div>
    {error && <Alert severity="error" onClose={() => { setError(''); setErrorGuidance(''); }}><Typography component="span">{error}</Typography>{errorGuidance && <Typography variant="body2" sx={{ mt: 1 }}>{errorGuidance}</Typography>}</Alert>}
    <Paper component="form" onSubmit={save} variant="outlined" sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h6">General</Typography><TextField disabled={!admin} label="Connector display name" value={data.connector_display_name} onChange={(e) => setData({ ...data, connector_display_name: e.target.value })} helperText="This name is displayed in the PEKA connector inventory." /><TextField disabled={!admin} label="Environment label" value={data.environment_label} onChange={(e) => setData({ ...data, environment_label: e.target.value })} /><TextField select disabled={!admin} label="Log level" value={data.log_level} onChange={(e) => setData({ ...data, log_level: e.target.value })}>{['DEBUG','INFO','WARNING','ERROR'].map((value) => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField>{admin && <Button disabled={busy} type="submit" variant="contained" sx={{ alignSelf: 'flex-start' }}>Save settings</Button>}</Stack></Paper>
    <Paper variant="outlined" sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h6">Certificates → Trusted Certificate Authorities</Typography><Alert severity="info">Enabled CAs extend the operating system trust store for verified Prometheus HTTPS connections.</Alert>{certificates.map((certificate) => <Paper key={certificate.id} variant="outlined" sx={{ p: 2 }}><Stack spacing={1}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" gap={1}><div><Typography fontWeight={700}>{certificate.name}</Typography><Typography variant="caption" color="text.secondary">{certificate.original_filename} · SHA-256 {certificate.fingerprint_sha256}</Typography></div><Typography color={certificate.expired ? 'error' : certificate.enabled ? 'success.main' : 'text.secondary'}>{certificate.expired ? 'Expired' : certificate.enabled ? 'Enabled' : 'Disabled'}</Typography></Stack><Typography variant="body2"><strong>Subject:</strong> {certificate.subject}</Typography><Typography variant="body2"><strong>Issuer:</strong> {certificate.issuer}</Typography><Typography variant="body2"><strong>Expires:</strong> {formatTimestamp(certificate.not_valid_after)}</Typography>{admin && <Stack direction="row" spacing={1}><Button disabled={busy || certificate.expired} onClick={() => void setCertificateState(certificate)}>{certificate.enabled ? 'Disable' : 'Enable'}</Button><Button disabled={busy} color="error" onClick={() => void deleteCertificate(certificate)}>Delete</Button></Stack>}</Stack></Paper>)}{certificates.length === 0 && <Typography color="text.secondary">No connector-managed certificate authorities have been added.</Typography>}{admin && <><Divider /><Typography fontWeight={600}>Add a CA certificate</Typography><TextField label="Certificate name" value={certificateName} onChange={(event) => setCertificateName(event.target.value)} /><Button component="label" variant="outlined" sx={{ alignSelf: 'flex-start' }}>Choose PEM file<input hidden type="file" accept=".pem,.crt,application/x-pem-file,application/x-x509-ca-cert" onChange={(event) => setCertificateFile(event.target.files?.[0] ?? null)} /></Button>{certificateFile && <Typography variant="body2">{certificateFile.name}</Typography>}<Button variant="contained" sx={{ alignSelf: 'flex-start' }} disabled={busy || !certificateName || !certificateFile} onClick={() => void uploadCertificate()}>Upload trusted CA</Button></>}</Stack></Paper>
    <Paper variant="outlined" sx={{ p: 3 }}><Stack spacing={2}><Stack direction="row" alignItems="center" spacing={2}><Typography variant="h6">PEKA Registration</Typography><ConnectionStatusBadge status={data.saas_status} />{data.saas_status === 'registering' && <CircularProgress size={20} />}</Stack><Typography variant="body2" color="text.secondary">Instance ID: <span style={{ fontFamily: 'monospace' }}>{data.instance_id}</span></Typography><Alert severity="info">Connected means the connector is communicating with PEKA. It does not mean source data has been uploaded or synchronized.</Alert>
      {!registered ? <><TextField disabled={!admin || busy} label="PEKA URL" value={data.saas_url ?? ''} onChange={(e) => setData({ ...data, saas_url: e.target.value })} helperText="Use HTTPS in production. Development may use http://host.docker.internal:<port>." />{admin ? <><TextField disabled={busy} required label="Registration Token" type="password" value={token} onChange={(e) => setToken(e.target.value)} autoComplete="off" helperText="One-time input; never stored by the connector" /><Stack direction="row" spacing={2}><Button disabled={busy || !data.saas_url} variant="outlined" onClick={() => void test()}>Test Connectivity</Button><Button disabled={busy || !data.saas_url || token.length < 20} variant="contained" onClick={() => void register(false)}>{busy ? 'Registering…' : 'Register'}</Button></Stack></> : <Alert severity="info">An administrator must register this connector.</Alert>}</> : <><Typography>PEKA URL: {data.saas_url}</Typography><Typography>Tenant ID: <span style={{ fontFamily: 'monospace' }}>{data.tenant_id}</span></Typography><Typography>Connector ID: <span style={{ fontFamily: 'monospace' }}>{data.connector_id}</span></Typography><Typography>Registered At: {formatTimestamp(data.registered_at)}</Typography><Typography>Last Heartbeat: {data.last_heartbeat_at ? `${relativeTimestamp(data.last_heartbeat_at)} (${formatTimestamp(data.last_heartbeat_at)})` : 'Never'}</Typography><Typography>Heartbeat Interval: {data.heartbeat_interval_seconds} seconds</Typography><Typography>Round-Trip Latency: {data.heartbeat_round_trip_ms === null ? 'Unavailable' : `${data.heartbeat_round_trip_ms.toFixed(1)} ms`}</Typography>{data.last_heartbeat_error && <Alert severity="warning">{customerFacingText(data.last_heartbeat_error)}</Alert>}{admin && <><Stack direction="row" spacing={2}><Button disabled={busy} variant="contained" onClick={() => void retry()}>Retry Now</Button><Button disabled={busy} color="error" variant="outlined" onClick={() => void unregister()}>Unregister Locally</Button></Stack><Divider /><Typography fontWeight={600}>Re-register</Typography><Alert severity="info">A new one-time registration token is required. Existing credentials are preserved if re-registration fails.</Alert><TextField disabled={busy} label="New Registration Token" type="password" value={token} onChange={(e) => setToken(e.target.value)} autoComplete="off" /><Button disabled={busy || token.length < 20} variant="outlined" sx={{ alignSelf: 'flex-start' }} onClick={() => void register(true)}>Re-register</Button><Alert severity="warning">Local unregister removes this appliance&apos;s local PEKA credentials. It does not delete or retire the connector record in PEKA.</Alert></>}</>}
    </Stack></Paper>
  </Stack>;
}
