import { Alert, Button, CircularProgress, Divider, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { useEffect, useState, type FormEvent } from 'react';

import { api } from '../api/client';
import type { ProductSettings } from '../api/types';
import { useAuth } from '../auth/AuthContext';
import { ConnectionStatusBadge } from '../components/ConnectionStatusBadge';
import { LoadingState } from '../components/LoadingState';
import { useToast } from '../components/ToastProvider';
import { formatTimestamp, relativeTimestamp } from '../utils/time';

export function SettingsPage() {
  const { user } = useAuth(); const toast = useToast(); const admin = user?.role === 'administrator';
  const [data, setData] = useState<ProductSettings | null>(null); const [token, setToken] = useState('');
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { void api.settings().then(setData).catch((e: Error) => setError(e.message)); }, []);
  const save = async (event: FormEvent) => { event.preventDefault(); if (!data) return; setBusy(true); try { const updated = await api.updateSettings({ connector_display_name: data.connector_display_name, environment_label: data.environment_label, log_level: data.log_level, timezone: data.timezone }); setData({ ...updated, saas_url: data.saas_url }); toast.show('Settings saved', 'success'); } catch (e) { setError(e instanceof Error ? e.message : 'Save failed'); } finally { setBusy(false); } };
  const test = async () => { if (!data?.saas_url) return; setBusy(true); try { const result = await api.testSaas(data.saas_url); toast.show(result.message, 'success'); } catch (e) { toast.show(e instanceof Error ? e.message : 'Connectivity test failed', 'error'); } finally { setBusy(false); } };
  const register = async (reregister: boolean) => { if (!data?.saas_url || !token || busy) return; if (reregister && !window.confirm('Re-register with a new token? Existing credentials remain active unless registration succeeds.')) return; setBusy(true); setError(''); try { const body = { saas_url: data.saas_url, registration_token: token, connector_display_name: data.connector_display_name, confirmed: reregister }; setData(reregister ? await api.reregisterSaas(body) : await api.registerSaas(body)); toast.show('Registration accepted; awaiting first heartbeat', 'success'); } catch (e) { setError(e instanceof Error ? e.message : 'Registration failed'); } finally { setToken(''); setBusy(false); } };
  const retry = async () => { setBusy(true); try { setData(await api.retryHeartbeat()); toast.show('Heartbeat attempt completed', 'success'); } catch (e) { setError(e instanceof Error ? e.message : 'Heartbeat retry failed'); } finally { setBusy(false); } };
  const unregister = async () => { if (!window.confirm("Local unregister removes this appliance's local SaaS credentials. It does not delete or retire the connector record in PEKA SaaS. Continue?")) return; setBusy(true); try { setData(await api.unregisterSaas()); setToken(''); toast.show('Local registration removed', 'success'); } catch (e) { setError(e instanceof Error ? e.message : 'Unregister failed'); } finally { setBusy(false); } };
  if (!data && !error) return <LoadingState />;
  if (!data) return <Alert severity="error">{error}</Alert>;
  const registered = Boolean(data.connector_id);
  return <Stack spacing={3}>
    <div><Typography variant="h4" fontWeight={700}>Settings</Typography><Typography color="text.secondary">UI-managed connector configuration</Typography></div>
    {error && <Alert severity="error" onClose={() => setError('')}>{error}</Alert>}
    <Paper component="form" onSubmit={save} variant="outlined" sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h6">General</Typography><TextField disabled={!admin} label="Connector display name" value={data.connector_display_name} onChange={(e) => setData({ ...data, connector_display_name: e.target.value })} /><TextField disabled={!admin} label="Environment label" value={data.environment_label} onChange={(e) => setData({ ...data, environment_label: e.target.value })} /><TextField select disabled={!admin} label="Log level" value={data.log_level} onChange={(e) => setData({ ...data, log_level: e.target.value })}>{['DEBUG','INFO','WARNING','ERROR'].map((value) => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField><TextField disabled={!admin} label="Time zone display preference" value={data.timezone} onChange={(e) => setData({ ...data, timezone: e.target.value })} />{admin && <Button disabled={busy} type="submit" variant="contained" sx={{ alignSelf: 'flex-start' }}>Save settings</Button>}</Stack></Paper>
    <Paper variant="outlined" sx={{ p: 3 }}><Stack spacing={2}><Stack direction="row" alignItems="center" spacing={2}><Typography variant="h6">SaaS Registration</Typography><ConnectionStatusBadge status={data.saas_status} />{data.saas_status === 'registering' && <CircularProgress size={20} />}</Stack><Typography variant="body2" color="text.secondary">Instance ID: <span style={{ fontFamily: 'monospace' }}>{data.instance_id}</span></Typography><Alert severity="info">Connected means the connector is communicating with PEKA SaaS. It does not mean source data has been uploaded or synchronized.</Alert>
      {!registered ? <><TextField disabled={!admin || busy} label="PEKA SaaS URL" value={data.saas_url ?? ''} onChange={(e) => setData({ ...data, saas_url: e.target.value })} helperText="Use HTTPS in production. Development may use http://host.docker.internal:<port>." />{admin ? <><TextField disabled={busy} required label="Registration Token" type="password" value={token} onChange={(e) => setToken(e.target.value)} autoComplete="off" helperText="One-time input; never stored by the connector" /><TextField disabled={busy} label="Connector Name" value={data.connector_display_name} onChange={(e) => setData({ ...data, connector_display_name: e.target.value })} /><Stack direction="row" spacing={2}><Button disabled={busy || !data.saas_url} variant="outlined" onClick={() => void test()}>Test Connectivity</Button><Button disabled={busy || !data.saas_url || token.length < 20} variant="contained" onClick={() => void register(false)}>{busy ? 'Registering…' : 'Register'}</Button></Stack></> : <Alert severity="info">An administrator must register this connector.</Alert>}</> : <><Typography>SaaS URL: {data.saas_url}</Typography><Typography>Tenant ID: <span style={{ fontFamily: 'monospace' }}>{data.tenant_id}</span></Typography><Typography>Connector ID: <span style={{ fontFamily: 'monospace' }}>{data.connector_id}</span></Typography><Typography>Registered At: {formatTimestamp(data.registered_at, data.timezone)}</Typography><Typography>Last Heartbeat: {data.last_heartbeat_at ? `${relativeTimestamp(data.last_heartbeat_at)} (${formatTimestamp(data.last_heartbeat_at, data.timezone)})` : 'Never'}</Typography><Typography>Heartbeat Interval: {data.heartbeat_interval_seconds} seconds</Typography><Typography>Round-Trip Latency: {data.heartbeat_round_trip_ms === null ? 'Unavailable' : `${data.heartbeat_round_trip_ms.toFixed(1)} ms`}</Typography>{data.last_heartbeat_error && <Alert severity="warning">{data.last_heartbeat_error}</Alert>}{admin && <><Stack direction="row" spacing={2}><Button disabled={busy} variant="contained" onClick={() => void retry()}>Retry Now</Button><Button disabled={busy} color="error" variant="outlined" onClick={() => void unregister()}>Unregister Locally</Button></Stack><Divider /><Typography fontWeight={600}>Re-register</Typography><Alert severity="info">A new one-time registration token is required. Existing credentials are preserved if re-registration fails.</Alert><TextField disabled={busy} label="New Registration Token" type="password" value={token} onChange={(e) => setToken(e.target.value)} autoComplete="off" /><Button disabled={busy || token.length < 20} variant="outlined" sx={{ alignSelf: 'flex-start' }} onClick={() => void register(true)}>Re-register</Button><Alert severity="warning">Local unregister removes this appliance&apos;s local SaaS credentials. It does not delete or retire the connector record in PEKA SaaS.</Alert></>}</>}
    </Stack></Paper>
  </Stack>;
}
