import AddIcon from '@mui/icons-material/Add'; import DeleteIcon from '@mui/icons-material/DeleteOutline'; import EditIcon from '@mui/icons-material/EditOutlined'; import HistoryIcon from '@mui/icons-material/History'; import PlayIcon from '@mui/icons-material/PlayArrow'; import VerifiedIcon from '@mui/icons-material/VerifiedOutlined';
import { Alert, Button, Chip, Dialog, DialogContent, DialogTitle, IconButton, Pagination, Paper, Stack, Switch, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Tooltip, Typography } from '@mui/material';
import { useCallback, useEffect, useState } from 'react';

import { api } from '../api/client'; import type { PaginatedScans, ScanDetail, ScanRecord, Source } from '../api/types'; import { useAuth } from '../auth/AuthContext'; import { LoadingState } from '../components/LoadingState'; import { SourceDialog } from '../components/SourceDialog'; import { useToast } from '../components/ToastProvider'; import { formatTimestamp } from '../utils/time';
import { enumLabel, scanDuration, scanRate } from '../utils/scans';

function SourceHealth({ source }: { source: Source }) {
  const state = !source.enabled ? 'Disabled' : source.scan_in_progress ? 'Scanning' : source.health_status === 'healthy' ? 'Healthy' : source.health_status === 'unhealthy' ? 'Failed' : 'Warning';
  const color = state === 'Healthy' ? 'success' : state === 'Failed' ? 'error' : state === 'Warning' ? 'warning' : state === 'Scanning' ? 'info' : 'default';
  return <Chip size="small" label={state} color={color} />;
}

export function SourcesPage() {
  const { user } = useAuth(); const admin = user?.role === 'administrator'; const toast = useToast();
  const [sources, setSources] = useState<Source[] | null>(null); const [error, setError] = useState('');
  const [dialog, setDialog] = useState(false); const [editing, setEditing] = useState<Source | null>(null); const [busy, setBusy] = useState(''); const [historySource, setHistorySource] = useState<Source | null>(null);
  const load = useCallback(() => { void api.listSources().then(setSources).catch((e: Error) => setError(e.message)); }, []); useEffect(load, [load]);
  const scan = async (source: Source) => { setBusy(source.id); try { const result = await api.scanSource(source.id); toast.show(`Scan completed: ${result.discovered_count} discovered`, 'success'); load(); } catch (e) { toast.show(e instanceof Error ? e.message : 'Scan failed', 'error'); load(); } finally { setBusy(''); } };
  const validate = async (source: Source) => { setBusy(source.id); try { const result = await api.validateSource(source.id); toast.show(result.message, 'success'); load(); } catch (e) { toast.show(e instanceof Error ? e.message : 'Validation failed', 'error'); load(); } finally { setBusy(''); } };
  const toggle = async (source: Source) => { try { await api.updateSource(source.id, { name: source.name, enabled: !source.enabled, configuration: source.configuration }); load(); } catch (e) { toast.show(e instanceof Error ? e.message : 'Update failed', 'error'); } };
  const remove = async (source: Source) => { if (!window.confirm(`Delete source “${source.name}” and its metadata history?`)) return; try { await api.deleteSource(source.id); load(); } catch (e) { toast.show(e instanceof Error ? e.message : 'Delete failed', 'error'); } };
  if (error) return <Alert severity="error">{error}</Alert>; if (!sources) return <LoadingState label="Loading sources" />;
  return <Stack spacing={3}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between"><div><Typography variant="h4" fontWeight={700}>Sources</Typography><Typography color="text.secondary">Configured connector data sources</Typography></div>{admin && <Button variant="contained" startIcon={<AddIcon />} onClick={() => { setEditing(null); setDialog(true); }}>Add Source</Button>}</Stack>
    {sources.length === 0 ? <Alert severity="info">No sources are configured. Add a Filesystem Documents source to begin discovery.</Alert> : <TableContainer component={Paper}><Table><TableHead><TableRow><TableCell>Name / Type</TableCell><TableCell>Path</TableCell><TableCell>Enabled</TableCell><TableCell>Health</TableCell><TableCell>Next Scan</TableCell><TableCell>Last Scheduled</TableCell><TableCell>Files Known</TableCell><TableCell>Last Error</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{sources.map((source) => <TableRow key={source.id}><TableCell><Typography fontWeight={600}>{source.name}</Typography><Typography variant="caption" color="text.secondary">Filesystem Documents</Typography></TableCell><TableCell sx={{ fontFamily: 'monospace', maxWidth: 260, overflowWrap: 'anywhere' }}>{source.configuration.path}</TableCell><TableCell>{admin ? <Switch checked={source.enabled} onChange={() => void toggle(source)} inputProps={{ 'aria-label': `Enable ${source.name}` }} /> : source.enabled ? 'Yes' : 'No'}</TableCell><TableCell><SourceHealth source={source} /></TableCell><TableCell>{formatTimestamp(source.next_scheduled_scan_at, 'Not scheduled')}</TableCell><TableCell>{formatTimestamp(source.last_scheduled_scan_at)}</TableCell><TableCell>{source.file_count}</TableCell><TableCell>{source.last_error ?? 'None'}</TableCell><TableCell align="right">{admin && <><Tooltip title="Validate"><span><IconButton aria-label={`Validate ${source.name}`} disabled={busy === source.id} onClick={() => void validate(source)}><VerifiedIcon /></IconButton></span></Tooltip><Tooltip title="Scan now"><span><IconButton aria-label={`Scan ${source.name}`} disabled={busy === source.id || !source.enabled} onClick={() => void scan(source)}><PlayIcon /></IconButton></span></Tooltip><Tooltip title="Edit"><IconButton aria-label={`Edit ${source.name}`} onClick={() => { setEditing(source); setDialog(true); }}><EditIcon /></IconButton></Tooltip></>}<Tooltip title="Scan history"><IconButton aria-label={`Scan history for ${source.name}`} onClick={() => setHistorySource(source)}><HistoryIcon /></IconButton></Tooltip>{admin && <Tooltip title="Delete"><IconButton aria-label={`Delete ${source.name}`} color="error" onClick={() => void remove(source)}><DeleteIcon /></IconButton></Tooltip>}</TableCell></TableRow>)}</TableBody></Table></TableContainer>}
    <SourceDialog open={dialog} source={editing} onClose={() => setDialog(false)} onSaved={() => { setDialog(false); load(); }} /><HistoryDialog source={historySource} onClose={() => setHistorySource(null)} />
  </Stack>;
}

function HistoryDialog({ source, onClose }: { source: Source | null; onClose: () => void }) {
  const [page, setPage] = useState(1); const [data, setData] = useState<PaginatedScans | null>(null); const [error, setError] = useState(''); const [detail, setDetail] = useState<ScanDetail | null>(null); const [detailLoading, setDetailLoading] = useState(false);
  useEffect(() => { setPage(1); setData(null); setError(''); }, [source]);
  useEffect(() => { if (!source) return; setData(null); void api.scanHistory(source.id, page).then(setData).catch((e: Error) => setError(e.message)); }, [source, page]);
  const openDetail = async (scan: ScanRecord) => { if (!source) return; setDetailLoading(true); try { setDetail(await api.scanDetail(source.id, scan.id)); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load scan details'); } finally { setDetailLoading(false); } };
  return <><Dialog open={Boolean(source)} onClose={onClose} fullWidth maxWidth="xl"><DialogTitle>Scan History — {source?.name}</DialogTitle><DialogContent>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}{!data && !error ? <LoadingState label="Loading scan history" /> : data?.items.length === 0 ? <Alert severity="info">No scans have run for this source.</Alert> : data && <><TableContainer><Table size="small"><TableHead><TableRow>{['Started','Completed','Duration','Trigger','Status','Discovered','Added','Changed','Unchanged','Missing','Failed','Average Rate'].map((item) => <TableCell key={item}>{item}</TableCell>)}</TableRow></TableHead><TableBody>{data.items.map((scan) => <TableRow hover tabIndex={0} key={scan.id} onClick={() => void openDetail(scan)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') void openDetail(scan); }} sx={{ cursor: 'pointer' }}><TableCell>{formatTimestamp(scan.started_at)}</TableCell><TableCell>{formatTimestamp(scan.completed_at, 'In progress')}</TableCell><TableCell>{scanDuration(scan)}</TableCell><TableCell>{enumLabel(scan.trigger)}</TableCell><TableCell>{enumLabel(scan.status)}</TableCell><TableCell>{scan.discovered_count}</TableCell><TableCell>{scan.added_count}</TableCell><TableCell>{scan.changed_count}</TableCell><TableCell>{scan.unchanged_count}</TableCell><TableCell>{scan.missing_count}</TableCell><TableCell>{scan.failed_count}</TableCell><TableCell>{scanRate(scan)}</TableCell></TableRow>)}</TableBody></Table></TableContainer><Pagination sx={{ mt: 2 }} page={page} count={Math.max(1, Math.ceil(data.total / data.page_size))} onChange={(_, value) => setPage(value)} /></>}</DialogContent></Dialog><ScanDetailDialog value={detail} loading={detailLoading} onClose={() => setDetail(null)} /></>;
}

function ScanDetailDialog({ value, loading, onClose }: { value: ScanDetail | null; loading: boolean; onClose: () => void }) {
  const facts = value ? [['Source', value.source_name], ['Trigger', enumLabel(value.trigger)], ['Started', formatTimestamp(value.started_at)], ['Completed', formatTimestamp(value.completed_at, 'In progress')], ['Duration', scanDuration(value)], ['Status', enumLabel(value.status)], ['Discovered', value.discovered_count], ['Added', value.added_count], ['Changed', value.changed_count], ['Unchanged', value.unchanged_count], ['Missing', value.missing_count], ['Failed', value.failed_count], ['Average Scan Rate', scanRate(value)], ['Correlation ID', value.correlation_id], ['Sanitized Error', value.error ?? 'None'], ['Log References', value.log_references.length ? value.log_references.join(', ') : 'None available']] : [];
  return <Dialog open={Boolean(value) || loading} onClose={onClose} fullWidth maxWidth="md"><DialogTitle>Scan Details</DialogTitle><DialogContent>{loading && !value ? <LoadingState label="Loading scan details" /> : <Stack spacing={1}>{facts.map(([name, fact]) => <div key={String(name)}><Typography variant="caption" color="text.secondary">{name}</Typography><Typography sx={{ overflowWrap: 'anywhere' }}>{fact}</Typography></div>)}</Stack>}</DialogContent></Dialog>;
}
