import AddIcon from '@mui/icons-material/Add'; import DeleteIcon from '@mui/icons-material/DeleteOutline'; import KeyIcon from '@mui/icons-material/Key';
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, MenuItem, Paper, Stack, Switch, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Tooltip, Typography } from '@mui/material';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { api } from '../api/client'; import type { LocalUser, Role } from '../api/types'; import { useAuth } from '../auth/AuthContext'; import { LoadingState } from '../components/LoadingState'; import { useToast } from '../components/ToastProvider';
export function UsersPage() { const { user: current } = useAuth(); const toast = useToast(); const [users, setUsers] = useState<LocalUser[] | null>(null); const [error, setError] = useState(''); const [open, setOpen] = useState(false); const [reset, setReset] = useState<LocalUser | null>(null);
  const load = useCallback(() => { void api.users().then(setUsers).catch((e: Error) => setError(e.message)); }, []); useEffect(load, [load]);
  const state = async (user: LocalUser) => { try { await api.setUserState(user.id, !user.is_active); load(); } catch (e) { toast.show(e instanceof Error ? e.message : 'Update failed', 'error'); } };
  const remove = async (user: LocalUser) => { if (!window.confirm(`Delete user “${user.username}”?`)) return; try { await api.deleteUser(user.id); load(); } catch (e) { toast.show(e instanceof Error ? e.message : 'Delete failed', 'error'); } };
  if (error) return <Alert severity="error">{error}</Alert>; if (!users) return <LoadingState />;
  return <Stack spacing={3}><Stack direction="row" justifyContent="space-between"><div><Typography variant="h4" fontWeight={700}>Users</Typography><Typography color="text.secondary">Local appliance access</Typography></div><Button variant="contained" startIcon={<AddIcon />} onClick={() => setOpen(true)}>Create user</Button></Stack>
    <TableContainer component={Paper}><Table><TableHead><TableRow><TableCell>Username</TableCell><TableCell>Role</TableCell><TableCell>Enabled</TableCell><TableCell>Last login</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{users.map((user) => <TableRow key={user.id}><TableCell>{user.username}</TableCell><TableCell>{user.role === 'administrator' ? 'Administrator' : 'Read Only'}</TableCell><TableCell><Switch checked={user.is_active} onChange={() => void state(user)} inputProps={{ 'aria-label': `Enable ${user.username}` }} /></TableCell><TableCell>{user.last_login_at ? new Date(user.last_login_at).toLocaleString() : 'Never'}</TableCell><TableCell align="right"><Tooltip title="Reset password"><IconButton onClick={() => setReset(user)}><KeyIcon /></IconButton></Tooltip><Tooltip title="Delete"><span><IconButton color="error" disabled={user.id === current?.id} onClick={() => void remove(user)}><DeleteIcon /></IconButton></span></Tooltip></TableCell></TableRow>)}</TableBody></Table></TableContainer>
    <UserDialog open={open} onClose={() => setOpen(false)} onSaved={() => { setOpen(false); load(); }} />
    <ResetDialog user={reset} onClose={() => setReset(null)} />
  </Stack>;
}
function UserDialog({ open, onClose, onSaved }: { open: boolean; onClose: () => void; onSaved: () => void }) { const [username, setUsername] = useState(''); const [role, setRole] = useState<Role>('read_only'); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState('');
  const submit = async (e: FormEvent) => { e.preventDefault(); try { await api.createUser({ username, role, password, confirm_password: confirm }); onSaved(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Create failed'); } };
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="xs" PaperProps={{ component: 'form', onSubmit: submit }}><DialogTitle>Create user</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}>{error && <Alert severity="error">{error}</Alert>}<TextField required label="Username" value={username} onChange={(e) => setUsername(e.target.value)} /><TextField select label="Role" value={role} onChange={(e) => setRole(e.target.value as Role)}><MenuItem value="administrator">Administrator</MenuItem><MenuItem value="read_only">Read Only</MenuItem></TextField><TextField required type="password" label="Password" value={password} onChange={(e) => setPassword(e.target.value)} /><TextField required type="password" label="Confirm password" value={confirm} onChange={(e) => setConfirm(e.target.value)} /></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button type="submit" variant="contained">Create</Button></DialogActions></Dialog>;
}
function ResetDialog({ user, onClose }: { user: LocalUser | null; onClose: () => void }) { const toast = useToast(); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const submit = async (e: FormEvent) => { e.preventDefault(); if (!user) return; try { await api.resetUserPassword(user.id, password, confirm); toast.show('Password reset', 'success'); onClose(); } catch (caught) { toast.show(caught instanceof Error ? caught.message : 'Reset failed', 'error'); } };
  return <Dialog open={Boolean(user)} onClose={onClose} fullWidth maxWidth="xs" PaperProps={{ component: 'form', onSubmit: submit }}><DialogTitle>Reset password for {user?.username}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField required type="password" label="New password" value={password} onChange={(e) => setPassword(e.target.value)} /><TextField required type="password" label="Confirm password" value={confirm} onChange={(e) => setConfirm(e.target.value)} /></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button type="submit" variant="contained">Reset</Button></DialogActions></Dialog>;
}
